name: snakes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  scoped_model: ^1.0.1
  flutter_svg: ^0.22.0
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  get_it: ^5.0.1

dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
